#!/bin/zsh

# git
git config --global core.editor vim

git config --global user.name hamadatomoki
git config --global user.email hamada.tomoki01@gmail.com

## alias
git config --global alias.co checkout
git config --global alias.br branch
git config --global alias.ci commit
git config --global alias.st status
git config --global alias.sw switch
git config --global alias.st status
git config --global alias.rs reset
git config --global alias.rsh '!git reset --hard'
git config --global alias.ad add
git config --global alias.ph push
git config --global alias.pl pull
git config --global alias.lo '!git log'
git config --global alias.lol '!git log --oneline'
git config --global alias.lod '!git log --graph --oneline --decorate=full'


git config --global init.defaultBranch main
git config --global commit.template ~/config/git/template/commit_message

## gh
gh config set editor vim
gh alias set br 'browse'
gh alias set is 'issue'
gh alias set cr 'create'
gh alias set --shell isc 'gh issue create --title "$1" --assignee "@me" -F ~/config/git/template/issue_basic.md && gh issue list --state=open --limit=1'

gh alias set rp 'repo'

