#!/bin/bash
#set -euxo pipefail

echo "Running detekt check..."

cachedFiles="$(git --no-pager diff --diff-filter=d --name-only --line-prefix=$(git rev-parse --show-toplevel)/ --cached)"
echo -e "\n"
echo "Cached Files:"
echo "$cachedFiles"
echo -e "\n"

detektInput=$(echo "$cachedFiles " | awk '{printf "%s%s", (NR==1 ? "" : ","), $0}')

if [ "$detektInput" = ' ' ]; then
  exit 0
fi

MODULES="$HOME/repos/config/modules"
DETEKT="$MODULES/detekt"
OUTPUT=$(detekt --auto-correct --input "$detektInput" --build-upon-default-config --config $DETEKT/detekt-config.yaml --report html:$DETEKT/reports/log.html --baseline $DETEKT/baseline.xml --plugins $DETEKT/detekt-formatting-1.23.7.jar 2>&1)
#OUTPUT=$(detekt --auto-correct --input "$detektInput" --build-upon-default-config --config $DETEKT/detekt-config.yaml --report html:$DETEKT/reports/log.html --baseline $DETEKT/baseline.xml --create-baseline --plugins $DETEKT/detekt-formatting-1.23.7.jar 2>&1)
EXIT_CODE=$?
if [ $EXIT_CODE -ne 0 ]; then
  echo "***********************************************"
  echo "                 detekt failed                 "
  echo " Please fix the above issues before committing "
  echo "***********************************************"
  echo $OUTPUT
  open $DETEKT/reports/log.html
  exit $EXIT_CODE
fi
