formatting:
  active: true
  android: true
  autoCorrect: true
  ClassName:
    active: true
  ContextReceiverMapping:
    active: true
  DiscouragedCommentLocation:
    active: true
  EnumWrapping:
    active: true
  FunctionSignature:
    active: true
    forceMultilineWhenParameterCountGreaterOrEqualThan: 1 # 
  IfElseBracing:
    active: true
  NoBlankLineInList:
    active: true
  NoConsecutiveComments:
    active: true
  NoSingleLineBlockComment:
    active: true
  TryCatchFinallySpacing:
    active: true
  TypeArgumentListSpacing:
    active: true
  TypeParameterListSpacing:
    active: true
  TrailingCommaOnDeclarationSite: #
    active: true
