return {
  {
    "nvim-treesitter/nvim-treesitter",
    opts = {
      ensure_installed = {
        "bash",
        "help",
        "eex",
        "elixir",
        "erlang",
        "heex",
        "html",
        "surface",
        "html",
        "javascript",
        "json",
        "lua",
        "markdown",
        "markdown_inline",
        "python",
        "query",
        "regex",
        "tsx",
        "typescript",
        "kotlin",
        "vim",
        "yaml",
      },
      highlight = { enable = true },
    },
  },
}
